name: deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
env:
  REACT_APP_GOOGLE_API_TOKEN: ${{vars.REACT_APP_GOOGLE_API_TOKEN}}
  REACT_APP_SANITY_PROJECT_ID: ${{vars.REACT_APP_SANITY_PROJECT_ID}}
  REACT_APP_SANITY_TOKEN: ${{vars.REACT_APP_SANITY_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Print env
        run: echo "API TOKEN $REACT_APP_GOOGLE_API_TOKEN, SANITY_P_ID $REACT_APP_SANITY_PROJECT_ID, SANITY_TOKEN $REACT_APP_SANITY_TOKEN"